### ISSUE TITLE
Build is failing; status?

### ISSUE THREAD

**Issue by jedbrown** [kali/blis-rs#2]
This is based on an older version of BLIS and has quite a bit more build dependencies than `openblas-src`. Would you be opposed to adopting their strategy (use Git submodule to obtain the source, thereby dropping deps on `flate2`, `git2`, and `reqwest`)? I'd like to be able to add this to `blas-src` because BLIS is [faster](https://github.com/flame/blis/blob/master/docs/Performance.md) than OpenBLAS in many important configurations. I can prepare a PR if you'd like, or let me know if you'd rather not maintain.

The more ambitious (perhaps multi-precision, multi-domain) plans in the README are interesting, but I don't foresee having time to move that forward anytime in the near future. In any case, `blis-src` as an implementation for `blas-src` is important and should be low maintenance.

**Comment by kali** [comment]
Hey, thanks for your interest in this crate, I had honestly forgotten it existed. I actually went a different way in the end, developing tract-linalg my own rust+asm library — strongly inspired by BLIS — for the needs of tract, so the ambitious plan in the README is moot as far as I'm concerned. That said, it is clear that BLIS is a better alternative than atlas and openblas, and the Rust ecosystem should be able benefit from this.

As much as I dislike submodules, I think it's probably a better way than my downloading approach. I'll gladly merge a PR in that sense to revive this crate.

Also I'm curious... I haven't followed BLIS too much these past months, what architectures are you focusing on ?

**Comment by jedbrown** [comment]
I have a local test working with `blas-src`. I'll update it and submit to that org once my PR lands and you make a release.
https://github.com/jedbrown/blas-src

BLIS is a lot better on Zen2 with threads, for example. Also on modern ARM. I just want it to be available at this stage -- my primary interests are elsewhere in the algebraic solvers stack.
